<?php
/**
 * WishlistSharingRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Wishlist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Wishlist\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WishlistSharingRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WishlistSharingRequest
 * @package     GeminiCommerce\Wishlist
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WishlistSharingRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WishlistSharingRequest"
     */
    public function testWishlistSharingRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wishlist_id"
     */
    public function testPropertyWishlistId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "permission"
     */
    public function testPropertyPermission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_grn"
     */
    public function testPropertyCustomerGrn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer_aggregation_id"
     */
    public function testPropertyCustomerAggregationId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
