<?php
/**
 * WishlistApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Wishlist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Wishlist Service
 *
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Wishlist\Test\Api;

use \GeminiCommerce\Wishlist\Configuration;
use \GeminiCommerce\Wishlist\ApiException;
use \GeminiCommerce\Wishlist\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WishlistApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Wishlist
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WishlistApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for wishlistAddItemToWishlist
     *
     * .
     *
     */
    public function testWishlistAddItemToWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistAreItemsInWishlists
     *
     * .
     *
     */
    public function testWishlistAreItemsInWishlists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistBulkCreateSharing
     *
     * Sharing endpoints.
     *
     */
    public function testWishlistBulkCreateSharing()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistBulkRemoveItemsFromWishlists
     *
     * BulkRemoveItemsFromWishlists removes items from wishlists..
     *
     */
    public function testWishlistBulkRemoveItemsFromWishlists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistBulkRevokeSharing
     *
     * .
     *
     */
    public function testWishlistBulkRevokeSharing()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistCreateWishlist
     *
     * .
     *
     */
    public function testWishlistCreateWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistDeleteWishlist
     *
     * .
     *
     */
    public function testWishlistDeleteWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistGetItemFromWishlist
     *
     * .
     *
     */
    public function testWishlistGetItemFromWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistGetWishlistById
     *
     * .
     *
     */
    public function testWishlistGetWishlistById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistGetWishlistBySharedCode
     *
     * .
     *
     */
    public function testWishlistGetWishlistBySharedCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistListWishlistItems
     *
     * .
     *
     */
    public function testWishlistListWishlistItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistListWishlists
     *
     * .
     *
     */
    public function testWishlistListWishlists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistMergeWishlists
     *
     * .
     *
     */
    public function testWishlistMergeWishlists()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistRemoveItemFromWishlist
     *
     * .
     *
     */
    public function testWishlistRemoveItemFromWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistUpdateItemInWishlist
     *
     * .
     *
     */
    public function testWishlistUpdateItemInWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wishlistUpdateWishlist
     *
     * .
     *
     */
    public function testWishlistUpdateWishlist()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
